### ISSUE TITLE
Curve LPT Pricing

### ISSUE THREAD

**Issue by 0xEinCodes** [PeggyJV/cellar-contracts#160]
We are trying to price Curve LP tokens with 2 underlying tokens.

To price correlated Curve LP pairs that do not implement `lp_price()`: Our logic is to safely price `coins[0]`and `coins[1]`, then find the minimum price between the two. We then take this minimum and multiply by the `virtual price`.

To price correlated Curve LP pairs that do implement `lp_price()`: Our logic safely prices `coins[0]`, then we multiply by `pool.lp_price()`.

Note for all pricing methods, we have a safe way of checking that the underlying pool is not in a re-entered state.

For more context, this query refers to the Curve pricing (needed for Curve integration) within the current [dev branch for the current audit](https://github.com/PeggyJV/cellar-contracts/tree/dev/macro-audit-14) and the incoming PR #157. 

Specific files of interest are [here](https://github.com/PeggyJV/cellar-contracts/blob/55032df73c97a332c1efca0d02743c5c2f8b1cc9/src/modules/price-router/Extensions/Curve/Curve2PoolExtension.sol) and [here](https://github.com/PeggyJV/cellar-contracts/tree/dev/macro-audit-14/src/modules/price-router/Extensions/Curve).

**Comment by crispymangoes** [comment]
Howdy Daniel! Appreciate your reply, for a bit more context the vast majority of pricing comes from Chainlink datafeeds.

When you say run fork simulations, we do have extensive simulations checking for reentrancy in curve pools, but could definitely use more tests that try to mess with the pools valuation. Would you recommend us trying to simulate large swaps in the pool to affect the LP value, or something else?

When you talk about v2 pools, am I right in thinking that those are pools with uncorrelated assets? Like [this](https://curve.fi/#/ethereum/pools/cvxeth/deposit), or even [this](https://curve.fi/#/ethereum/pools/factory-crypto-210/deposit). If so, any v2 pools we price are priced using `lp_price` multiplied by a safe `coins[0]` value.

Also I saw your amazing tweet thread [here](https://twitter.com/danielvf/status/1729966217710956991) in your findings were you only able to drastically increase the price oracle values, or were you able to also decrease them?

Also also on this note ^^ did you find any issues with using the `price_oracle` values in ETH/FRXETH, WETH/FRXETH, or OETH/ETH? We do not have any products using those pools for pricing yet, but planned to in the future.

Thank you so much :)

**Comment by crispymangoes** [comment]
> Howdy Daniel! Appreciate your reply, for a bit more context the vast majority of pricing comes from Chainlink datafeeds.
> 
> When you say run fork simulations, we do have extensive simulations checking for reentrancy in curve pools, but could definitely use more tests that try to mess with the pools valuation. Would you recommend us trying to simulate large swaps in the pool to affect the LP value, or something else?
> 
> When you talk about v2 pools, am I right in thinking that those are pools with uncorrelated assets? Like [this](https://curve.fi/#/ethereum/pools/cvxeth/deposit), or even [this](https://curve.fi/#/ethereum/pools/factory-crypto-210/deposit). If so, any v2 pools we price are priced using `lp_price` multiplied by a safe `coins[0]` value.
> 
> Also I saw your amazing tweet thread [here](https://twitter.com/danielvf/status/1729966217710956991) in your findings were you only able to drastically increase the price oracle values, or were you able to also decrease them?
> 
> Also also on this note ^^ did you find any issues with using the `price_oracle` values in ETH/FRXETH, WETH/FRXETH, or OETH/ETH? We do not have any products using those pools for pricing yet, but planned to in the future.
> 
> Thank you so much :)



> I'd run fork simulations to make sure, but if you are using a Curve V1 pool with a fixed center point, and do have good, safe prices on each coin, then I would think the proposed algo of taking the min coin price times the virtual price is likely to be a safe way of doing things.
> 
> If you use a v2 pool, the midpoint (price_scale) can change, and so I'm not 100% sure how it would work.
> 
> And this is obviously only as good as the coin prices coming into the system.
> 
> But above all fork test it on the specific pool you are using!



> I'd run fork simulations to make sure, but if you are using a Curve V1 pool with a fixed center point, and do have good, safe prices on each coin, then I would think the proposed algo of taking the min coin price times the virtual price is likely to be a safe way of doing things.
> 
> If you use a v2 pool, the midpoint (price_scale) can change, and so I'm not 100% sure how it would work.
> 
> And this is obviously only as good as the coin prices coming into the system.
> 
> But above all fork test it on the specific pool you are using!

Howdy Daniel! Appreciate your reply, for a bit more context the vast majority of pricing comes from Chainlink datafeeds.

When you say run fork simulations, we do have extensive simulations checking for reentrancy in curve pools, but could definitely use more tests that try to mess with the pools valuation. Would you recommend us trying to simulate large swaps in the pool to affect the LP value, or something else?

When you talk about v2 pools, am I right in thinking that those are pools with uncorrelated assets? Like [this](https://curve.fi/#/ethereum/pools/cvxeth/deposit), or even [this](https://curve.fi/#/ethereum/pools/factory-crypto-210/deposit). If so, any v2 pools we price are priced using `lp_price` multiplied by a safe `coins[0]` value.

Also I saw your amazing tweet thread [here](https://twitter.com/danielvf/status/1729966217710956991) in your findings were you only able to drastically increase the price oracle values, or were you able to also decrease them?

Also also on this note ^^ did you find any issues with using the `price_oracle` values in ETH/FRXETH, WETH/FRXETH, or OETH/ETH? We do not have any products using those pools for pricing yet, but planned to in the future.

Thank you so much :)

**Comment by crispymangoes** [comment]
> I'd run fork simulations to make sure, but if you are using a Curve V1 pool with a fixed center point, and do have good, safe prices on each coin, then I would think the proposed algo of taking the min coin price times the virtual price is likely to be a safe way of doing things.
> 
> If you use a v2 pool, the midpoint (price_scale) can change, and so I'm not 100% sure how it would work.
> 
> And this is obviously only as good as the coin prices coming into the system.
> 
> But above all fork test it on the specific pool you are using!

Howdy Daniel! Appreciate your reply, for a bit more context the vast majority of pricing comes from Chainlink datafeeds.

When you say run fork simulations, we do have extensive simulations checking for reentrancy in curve pools, but could definitely use more tests that try to mess with the pools valuation. Would you recommend us trying to simulate large swaps in the pool to affect the LP value, or something else?

When you talk about v2 pools, am I right in thinking that those are pools with uncorrelated assets? Like [this](https://curve.fi/#/ethereum/pools/cvxeth/deposit), or even [this](https://curve.fi/#/ethereum/pools/factory-crypto-210/deposit). If so, any v2 pools we price are priced using `lp_price` multiplied by a safe `coins[0]` value.

Also I saw your amazing tweet thread [here](https://twitter.com/danielvf/status/1729966217710956991) in your findings were you only able to drastically increase the price oracle values, or were you able to also decrease them?

Also also on this note ^^ did you find any issues with using the `price_oracle` values in ETH/FRXETH, WETH/FRXETH, or OETH/ETH? We do not have any products using those pools for pricing yet, but planned to in the future.

Thank you so much :)
