### ISSUE TITLE
test(CellarRouter): add test against mainnet for `depositAndSwapIntoCellar`

### ISSUE THREAD

**Issue by brianle83** [PeggyJV/cellar-contracts#24]
## Testcases to Cover
- [ ] Test swap before depositing using Uniswap V2 router on mainnet fork.
- [ ] Test swap before depositing using Uniswap V3 router on mainnet fork.

**Comment by crispymangoes** [comment]
Test comment

**Comment by brianle83** [comment]
Closed and merged by @crispymangoes [here](https://github.com/PeggyJV/cellar-contracts/pull/28).
